#!/bin/bash
cat cmd2realtest | sed -e s/one/o1e/g -e s/two/t2o/g -e s/three/thr3e/g -e s/four/fo4ur/g -e s/five/f5e/g -e s/six/s6x/g -e s/seven/s7n/g -e s/eight/e8t/g -e s/nine/n9e/g  | sed -r "s/[[:alpha:]]+//g" | sed  "s/^\([[:digit:]]\{1,1\}\)$/\1\1/"  |  sed "s/^\([[:digit:]]\)[[:digit:]]\{1,255\}\([[:digit:]]\)$/\1\2/" | sed "2,$ a\+" | sed "$,$ a\p" | dc

